"""add external_id to search_locations

Revision ID: f29e46885ef2
Revises: 04a17d4e0656
Create Date: 2025-06-01 10:04:02.585194

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f29e46885ef2"
down_revision: Union[str, None] = "04a17d4e0656"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_search_history_id"), table_name="search_history")
    op.drop_index(op.f("ix_search_history_user_id"), table_name="search_history")
    op.drop_table("search_history")
    op.drop_index(op.f("ix_export_history_id"), table_name="export_history")
    op.drop_table("export_history")
    op.add_column(
        "search_locations", sa.Column("external_id", sa.String(), nullable=True)
    )
    op.add_column(
        "search_locations", sa.Column("updated_at", sa.DateTime(), nullable=True)
    )
    op.create_index(
        "ix_location_coords", "search_locations", ["latitude", "longitude"], unique=True
    )
    op.create_index(
        "ix_location_name",
        "search_locations",
        ["city", "state", "country"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_location_name", table_name="search_locations")
    op.drop_index("ix_location_coords", table_name="search_locations")
    op.drop_column("search_locations", "updated_at")
    op.drop_column("search_locations", "external_id")
    op.create_table(
        "export_history",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("export_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "export_params",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("error_message", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("export_history_pkey")),
    )
    op.create_index(
        op.f("ix_export_history_id"), "export_history", ["id"], unique=False
    )
    op.create_table(
        "search_history",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("query", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "searched_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("search_history_pkey")),
    )
    op.create_index(
        op.f("ix_search_history_user_id"), "search_history", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_search_history_id"), "search_history", ["id"], unique=False
    )
    # ### end Alembic commands ###
